### PR TITLE
#1248 add checks to determine if update needs to be sent

### PR DESCRIPTION
**Pull request by junaidzm13**

### CODE REVIEW

**Comment by junaidzm13** [comment]
Screenshot 2024-03-01 at 12 22 38 PM

**Comment by chrisjstevo** [comment]
Hi, 

This looks good, but I have one question. with the big data provider the index of the order can change in a dataset (due to sorting). But they key may not. 

For example if I have 10 rows, and key "A" is at top and key "J" is at bottom, both exist in the table. When a reverse alpha sort them, J is now at index 0, and A at 9. From a key perspective they both still exist, but their indices have changed. 

I think you need to not only check that the key and data has not changed, but for big data you need to make sure index is still pointing to that key also. 

Make sense?

Chris

**Comment by junaidzm13** [comment]
Not sure why, but I can't seem to reply to your comment @chrisjstevo. So replying here:

It totally makes sense, thanks for pointing that out!

I've updated the PR - now I'm checking fetched row at a given index against the row in the table at the same index. Which performs all the required checks. Lmk what you think.

**Comment by chrisjstevo** [comment]
I also can't replay to your comment :-) but looks good. Will merge now.

**Pull request merged**
